# Generated by Django 5.0 on 2026-04-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_leaderboardentry_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='gamepad', max_length=100)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.game'),
        ),
    ]
