# Generated by Django 5.0 on 2026-04-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_question_quizcategory_option_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.quizcategory'),
        ),
    ]
